version: "3.9"
services:
  haas_alert_ingest:
    build:
      context: .
      dockerfile: Dockerfile
    image: haas_alert_ingest
    ports:
      - 8080:8080
    environment:
      HAAS_API_ENDPOINT: ${HAAS_API_ENDPOINT}
      HAAS_AUTH_ENDPOINT: ${HAAS_AUTH_ENDPOINT}
      HAAS_WSS_ENDPOINT: ${HAAS_WSS_ENDPOINT}
      PROJECT_ID: ${PROJECT_ID}
      HAAS_AUTH_USERNAME_KEY: ${HAAS_AUTH_USERNAME_KEY}
      HAAS_AUTH_PASSWORD_KEY: ${HAAS_AUTH_PASSWORD_KEY}
      HAAS_BEARER_TOKEN_KEY: ${HAAS_BEARER_TOKEN_KEY}
      HAAS_REFRESH_TOKEN_KEY: ${HAAS_REFRESH_TOKEN_KEY}
      HAAS_API_ID: ${HAAS_API_ID}
      HEARTBEAT_TOPIC: ${HEARTBEAT_TOPIC}
      LOCATION_TOPIC: ${LOCATION_TOPIC}
      POINT_TOPIC: ${POINT_TOPIC}
      THING_TOPIC: ${THING_TOPIC}
      GOOGLE_APPLICATION_CREDENTIALS: "/usr/src/app/haas_websocket/gcp_credentials.json"